version: "3.5"

services:
  nginx:
    image: nginx:latest
    restart: always
    command: bash -c "service nginx start && tail -f /dev/null"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  django:
    image: <backend_docker_image>
    env_file:
      - ./<project_name>.env

  redis:
    restart: always
    image: redis:latest
    command: redis-server

  celery:
    image: <backend_docker_image>
    env_file:
      - ./<project_name>.env
    depends_on:
      - redis
      - django
    command: /code/run/celery.sh
